export const BRAND = "Byte & Brackets"
export const BRAND_SHORT = "B&B"
export const SITE_URL = "https://byteandbrackets.dev"

export const NAV_LINKS = ["Projects", "Services", "Process", "Studio", "Contact"]

export const CONTACT_EMAIL = "hello@byteandbrackets.dev"
export const LOCATION = "Remote — Berlin / NYC"
export const AVAILABILITY = "Taking projects for Q3"

export const SOCIALS = [
  { label: "GitHub", url: "#" },
  { label: "X", url: "#" },
  { label: "LinkedIn", url: "#" },
  { label: "Read.cv", url: "#" },
]

export const HERO_THESIS =
  "Product-engineering studio. We design, build, and ship the software your roadmap keeps pushing to next quarter."

export const STUDIO_HEADLINE = "We close the gap between the demo and the product."

export const STUDIO_TEXT =
  "Byte & Brackets is a small senior team. No account managers, no handoffs to juniors — the people who scope your project are the people who write the code. We take ambiguous briefs, turn them into shipped software, and stay until it runs in production."

export const STATS = [
  { value: "40+", label: "products shipped", icon: "/icons/cursor.webp" },
  { value: "6 wks", label: "median MVP", icon: "/icons/lego.webp" },
  { value: "12", label: "industries", icon: "/icons/moon.webp" },
  { value: "100%", label: "senior engineers", icon: "/icons/smile.webp" },
]

export const FOUNDER = {
  portrait: "/portrait/jack.webp",
  name: "Ava Renström",
  role: "Founder · Engineering Lead",
}

export const TICKER = [
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "PostgreSQL",
  "Rust",
  "Python",
  "Go",
  "GraphQL",
  "Docker",
  "Redis",
  "Stripe",
  "Tailwind",
  "Vercel",
]

export const SERVICES = [
  {
    number: "01",
    name: "Product Engineering",
    description:
      "Full-stack web apps and SaaS platforms built to ship. React, Next.js, typed end-to-end, tested, and deployed on infrastructure you own.",
    tags: ["Web apps", "SaaS", "APIs"],
  },
  {
    number: "02",
    name: "AI Integration",
    description:
      "LLM features that survive contact with real users — agents, RAG pipelines, evals, and guardrails wired into your product, not bolted on.",
    tags: ["Agents", "RAG", "Evals"],
  },
  {
    number: "03",
    name: "Design Systems",
    description:
      "Interfaces and component libraries that stay consistent as the team grows. Tokens, accessibility, and motion handled at the source.",
    tags: ["UI / UX", "Components", "A11y"],
  },
  {
    number: "04",
    name: "Cloud & Infra",
    description:
      "Deploy, observe, and scale without a platform team. CI/CD, infrastructure-as-code, and monitoring set up so releases are boring.",
    tags: ["CI/CD", "IaC", "Observability"],
  },
  {
    number: "05",
    name: "MVP Sprints",
    description:
      "Zero to a usable product in weeks, not quarters. A fixed-scope sprint that gets a real build in front of real users fast.",
    tags: ["0 → 1", "Prototype", "Validate"],
  },
]

export const PROCESS = [
  {
    number: "01",
    name: "Discovery",
    description: "We pin down the real problem, the constraints, and what success actually looks like before a line is written.",
  },
  {
    number: "02",
    name: "Architecture",
    description: "We choose the stack and shape the system for where you'll be in two years, not just the demo.",
  },
  {
    number: "03",
    name: "Build",
    description: "Weekly shippable increments. You see working software every Friday, not a status deck.",
  },
  {
    number: "04",
    name: "Ship",
    description: "We deploy to production, wire up monitoring, and hand over docs your team can actually run.",
  },
  {
    number: "05",
    name: "Scale",
    description: "We stay on retainer to harden, extend, and tune as your usage grows.",
  },
]

export const PROJECTS = [
  {
    number: "01",
    client: "Ledgerline",
    scope: "Fintech platform",
    year: "2025",
    outcome: "Rebuilt their finance ops tool from a spreadsheet into a real product. Month-end close went from four days to a single afternoon.",
    stack: ["Next.js", "Postgres", "Stripe"],
    image: "/projects/p01.webp",
    video: "/marquee/aethera.mp4",
    slug: "ledgerline",
    liveUrl: "#",
    duration: "5 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "Finance ran on a fragile web of spreadsheets — month-end close took four days and broke every time someone touched a formula.",
    approach: "We modelled the close as a real workflow, rebuilt it as a typed Next.js app on Postgres, and wired Stripe for reconciliation.",
    result: "Close dropped from four days to a single afternoon, with an audit trail finance trusts.",
  },
  {
    number: "02",
    client: "Northwind",
    scope: "Healthcare portal",
    year: "2025",
    outcome: "Designed and shipped a patient portal for records, scheduling, and secure messaging — live across 40 clinics in under five months.",
    stack: ["React", "Node", "HIPAA"],
    image: "/projects/p02.webp",
    video: "/marquee/asme.mp4",
    slug: "northwind",
    liveUrl: "#",
    duration: "5 months",
    services: ["Product Engineering", "Design Systems"],
    challenge: "Patients juggled phone calls and paper for records, scheduling, and messaging across dozens of clinics.",
    approach: "We designed and shipped a HIPAA-compliant portal in React and Node, rolling it out clinic by clinic.",
    result: "Live across forty clinics in under five months, with secure messaging patients actually use.",
  },
  {
    number: "03",
    client: "Cargo",
    scope: "Logistics dashboard",
    year: "2024",
    outcome: "Realtime fleet and shipment tracking that holds steady at well over a million events a day without a dedicated infra team.",
    stack: ["Rust", "Realtime", "AWS"],
    image: "/projects/p03.webp",
    video: "/marquee/celestia.mp4",
    slug: "cargo",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "Fleet and shipment data arrived faster than their old dashboard could render — operators were flying blind.",
    approach: "We built a realtime pipeline in Rust on AWS, streaming events to a dashboard tuned for density.",
    result: "Holds steady at over a million events a day with no dedicated infra team.",
  },
  {
    number: "04",
    client: "Verra",
    scope: "AI writing tool",
    year: "2025",
    outcome: "Took an LLM demo to a product people pay for — retrieval, evals, and team workspaces that survived real usage from day one.",
    stack: ["LLM agents", "RAG", "Evals"],
    image: "/projects/p04.webp",
    video: "/marquee/codenest.mp4",
    slug: "verra",
    liveUrl: "#",
    duration: "3 months",
    services: ["AI Integration", "Product Engineering"],
    challenge: "An impressive LLM demo kept falling over the moment real users and real documents hit it.",
    approach: "We added retrieval, evals, and guardrails, and built team workspaces around the model — not bolted on.",
    result: "A product people pay for that survived real usage from day one.",
  },
  {
    number: "05",
    client: "Tidepool",
    scope: "Analytics SaaS",
    year: "2024",
    outcome: "A self-serve analytics product that keeps queries under half a second across billions of rows. No more waiting on the data team.",
    stack: ["TypeScript", "ClickHouse", "Edge"],
    image: "/projects/p05.webp",
    video: "/marquee/designpro.mp4",
    slug: "tidepool",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "Every question for the data team meant a ticket and a wait; self-serve analytics felt impossible at their scale.",
    approach: "We built a self-serve product on ClickHouse with an edge query layer tuned for sub-second response.",
    result: "Queries stay under half a second across billions of rows.",
  },
  {
    number: "06",
    client: "Forge",
    scope: "Developer tooling",
    year: "2024",
    outcome: "A CI platform that runs and caches builds across a global edge. Pipelines that used to take twenty minutes now finish in seven.",
    stack: ["Go", "Docker", "Edge"],
    image: "/projects/p06.webp",
    video: "/marquee/evr-ventures.mp4",
    slug: "forge",
    liveUrl: "#",
    duration: "5 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "CI pipelines took twenty minutes, throttling how fast their team could ship.",
    approach: "We built a CI platform in Go that runs and caches builds across a global edge.",
    result: "Pipelines that took twenty minutes now finish in seven.",
  },
  {
    number: "07",
    client: "Meridian",
    scope: "Climate reporting",
    year: "2023",
    outcome: "Carbon accounting for mid-market manufacturers — mapped hundreds of messy supply chains into reports auditors actually accept.",
    stack: ["Python", "Postgres", "Next.js"],
    image: "/projects/p07.webp",
    video: "/marquee/luminex.mp4",
    slug: "meridian",
    liveUrl: "#",
    duration: "6 months",
    services: ["Product Engineering", "AI Integration"],
    challenge: "Mid-market manufacturers had messy supply chains and no way to produce carbon reports auditors would accept.",
    approach: "We built a Python and Postgres pipeline that maps tangled supply chains into structured, auditable reports.",
    result: "Hundreds of supply chains mapped into reports auditors actually accept.",
  },
  {
    number: "08",
    client: "Salt",
    scope: "Commerce engine",
    year: "2023",
    outcome: "A headless storefront and subscription engine for a fast-growing DTC brand, tuned until checkout stopped leaking customers.",
    stack: ["Next.js", "Stripe", "Edge"],
    image: "/projects/p08.webp",
    video: "/marquee/new-era.mp4",
    slug: "salt",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "Design Systems"],
    challenge: "A fast-growing DTC brand was leaking customers at checkout and couldn't iterate on their storefront.",
    approach: "We built a headless storefront and subscription engine on Next.js and Stripe, then tuned the checkout.",
    result: "Checkout stopped leaking customers and subscriptions scaled cleanly.",
  },
  {
    number: "09",
    client: "Quanta",
    scope: "Data platform",
    year: "2025",
    outcome: "Unified seven scattered data sources into one warehouse with self-serve dashboards, so the ops team stopped filing tickets for every report.",
    stack: ["Python", "dbt", "Snowflake"],
    image: "/projects/p09.webp",
    video: "/marquee/nexora.mp4",
    slug: "quanta",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "Seven scattered data sources meant the ops team filed a ticket for every report they needed.",
    approach: "We unified everything into one warehouse with dbt models and self-serve dashboards.",
    result: "Ops stopped filing tickets — they answer their own questions now.",
  },
  {
    number: "10",
    client: "Hearth",
    scope: "Proptech marketplace",
    year: "2024",
    outcome: "Built a two-sided rental marketplace from scratch — listings, payments, and messaging — to a live launch in three markets in four months.",
    stack: ["Next.js", "Postgres", "Stripe"],
    image: "/projects/p10.webp",
    video: "/marquee/orbit-web3.mp4",
    slug: "hearth",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "MVP Sprints"],
    challenge: "A two-sided rental marketplace had to launch in three markets fast, with payments and messaging from day one.",
    approach: "We built listings, payments, and messaging on Next.js, Postgres, and Stripe from scratch.",
    result: "Live in three markets in four months.",
  },
  {
    number: "11",
    client: "Beacon",
    scope: "Education platform",
    year: "2024",
    outcome: "A live-cohort learning product with video, assignments, and grading that scaled past ten thousand concurrent students without a wobble.",
    stack: ["React", "Node", "Realtime"],
    image: "/projects/p12.webp",
    video: "/marquee/planet-orbit.mp4",
    slug: "beacon",
    liveUrl: "#",
    duration: "5 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "A live-cohort learning product needed video, assignments, and grading that wouldn't buckle under load.",
    approach: "We built it on React and Node with a realtime layer designed for spikes.",
    result: "Scaled past ten thousand concurrent students without a wobble.",
  },
  {
    number: "12",
    client: "Lumen",
    scope: "Energy IoT",
    year: "2023",
    outcome: "Realtime monitoring for distributed solar sites — ingesting device telemetry and surfacing faults before crews are dispatched.",
    stack: ["Rust", "Timescale", "Edge"],
    image: "/projects/p13.webp",
    video: "/marquee/skyelite.mp4",
    slug: "lumen",
    liveUrl: "#",
    duration: "4 months",
    services: ["Product Engineering", "Cloud & Infra"],
    challenge: "Distributed solar sites generated telemetry no one could act on until something had already failed.",
    approach: "We built realtime monitoring in Rust on Timescale, surfacing faults before crews are dispatched.",
    result: "Faults surface before crews roll, cutting wasted truck-rolls.",
  },
  {
    number: "13",
    client: "Atlas",
    scope: "Internal tooling",
    year: "2025",
    outcome: "Replaced a tangle of spreadsheets and Zapier flows with one internal admin app the whole company actually trusts as the source of truth.",
    stack: ["Next.js", "Postgres", "tRPC"],
    image: "/projects/p14.webp",
    video: "/marquee/space-voyage.mp4",
    slug: "atlas",
    liveUrl: "#",
    duration: "3 months",
    services: ["Product Engineering", "Design Systems"],
    challenge: "Operations ran on a tangle of spreadsheets and Zapier flows no one fully trusted.",
    approach: "We replaced it with one internal admin app on Next.js, Postgres, and tRPC as the source of truth.",
    result: "The whole company now trusts one source of truth.",
  },
  {
    number: "14",
    client: "Vesper",
    scope: "Consumer app",
    year: "2025",
    outcome: "A habit-tracking mobile app taken from Figma to the App Store in eight weeks, with sync and offline support that held up on day-one traffic.",
    stack: ["React Native", "Expo", "Supabase"],
    image: "/projects/p15.webp",
    video: "/marquee/stellar-ai.mp4",
    slug: "vesper",
    liveUrl: "#",
    duration: "8 weeks",
    services: ["MVP Sprints", "Product Engineering"],
    challenge: "A habit-tracking app had to go from Figma to the App Store fast, with sync and offline that just worked.",
    approach: "We built it in React Native and Expo on Supabase, with offline-first sync.",
    result: "Figma to App Store in eight weeks, holding up on day-one traffic.",
  },
]

export const TEAM = [
  {
    name: "Ava Renström",
    role: "Founder · Eng Lead",
    note: "Ex-infra at a payments scale-up. Writes the gnarly bits.",
  },
  {
    name: "Diego Cruz",
    role: "Principal Engineer",
    note: "Full-stack generalist. Believes boring tech ships faster.",
  },
  {
    name: "Mara Okafor",
    role: "Design Lead",
    note: "Design systems and motion. Keeps the brackets straight.",
  },
  {
    name: "Jun Kim",
    role: "AI Engineer",
    note: "Agents, evals, retrieval. Allergic to hand-wavy demos.",
  },
]

export const TESTIMONIALS = [
  {
    tag: "shipped",
    quote: "Month-end close went from four days to a single afternoon. They stayed until it ran in production.",
    name: "Maya Chen",
    role: "CTO",
    company: "Ledgerline",
  },
  {
    tag: "no handoffs",
    quote: "Live across forty clinics in under five months — and the people who scoped it are the people who wrote the code.",
    name: "David Okonkwo",
    role: "VP Engineering",
    company: "Northwind",
  },
  {
    tag: "at scale",
    quote: "Realtime tracking that holds steady at over a million events a day, with no infra team of our own.",
    name: "Priya Nair",
    role: "Head of Ops",
    company: "Cargo",
  },
]
